version: 2
jobs:
  deploy_app:
    docker:
       - image: circleci/node:10-browsers
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: node_modulesのインストール
          command: |
            yarn
      - run:
         name: ビルド
         command: |
           yarn build
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします

workflows:
  version: 2
  build-deploy: # ワークフローの名前
    jobs:
      - deploy_app: # 上で定義したジョブを指定します
          filters:
            branches:
              only: master # masterブランチのみを実行対象とします